'use client';

import { useState, useEffect, useCallback, useMemo } from 'react';
import { useParams } from 'next/navigation';
import { QuickShotGenerator } from '@/components/quick-shot/QuickShotGenerator';
import { StorageMedia } from '@/components/ui/storage-image';
import { Lightbox, type LightboxImage } from '@/components/ui/lightbox';
import { ProjectBibleButton } from '@/components/bible/ProjectBible';
import {
  Loader2,
  Maximize2,
  Trash2,
  Camera,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { toast } from 'sonner';
import type { Shot, AspectRatio } from '@/types/database';

interface RushImage {
  id: string;
  project_id: string;
  user_id: string;
  url: string;
  prompt: string | null;
  aspect_ratio: string | null;
  model: string | null;
  created_at: string;
}

export default function RushPage() {
  const params = useParams();
  const projectId = params.projectId as string;

  // State
  const [images, setImages] = useState<RushImage[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [lightboxOpen, setLightboxOpen] = useState(false);
  const [lightboxIndex, setLightboxIndex] = useState(0);
  const [hoveredImage, setHoveredImage] = useState<string | null>(null);
  const [projectAspectRatio, setProjectAspectRatio] = useState<AspectRatio>('16:9');

  // Fetch rush images
  const fetchImages = useCallback(async () => {
    try {
      setIsLoading(true);
      const res = await fetch(`/api/projects/${projectId}/rush`);
      if (res.ok) {
        const data = await res.json();
        setImages(data.images || []);
        if (data.aspectRatio) {
          setProjectAspectRatio(data.aspectRatio);
        }
      }
    } catch (error) {
      console.error('Failed to fetch rush images:', error);
    } finally {
      setIsLoading(false);
    }
  }, [projectId]);

  useEffect(() => {
    fetchImages();
  }, [fetchImages]);

  // Handle shots generated by QuickShotGenerator
  // The API stores directly to rush_images, but returns Shot-like objects
  const handleShotsGenerated = useCallback((shots: Shot[]) => {
    // Convert shots to rush images and add to state
    const newImages: RushImage[] = shots.map(shot => ({
      id: shot.id,
      project_id: projectId,
      user_id: '',
      url: shot.storyboard_image_url || '',
      prompt: shot.description || null,
      aspect_ratio: null,
      model: null,
      created_at: shot.created_at || new Date().toISOString(),
    }));

    setImages(prev => [...newImages, ...prev]);
  }, [projectId]);

  // Delete image
  const handleDelete = async (imageId: string) => {
    if (!confirm('Supprimer cette image ?')) return;

    try {
      const res = await fetch(`/api/projects/${projectId}/rush?id=${imageId}`, {
        method: 'DELETE',
      });

      if (res.ok) {
        setImages((prev) => prev.filter((img) => img.id !== imageId));
        toast.success('Image supprimee');
      }
    } catch (error) {
      console.error('Failed to delete:', error);
      toast.error('Erreur de suppression');
    }
  };

  // Lightbox
  const lightboxImages = useMemo((): LightboxImage[] => {
    return images.map((img) => ({
      id: img.id,
      url: img.url,
      description: img.prompt || undefined,
    }));
  }, [images]);

  const openLightbox = (index: number, e: React.MouseEvent) => {
    e.stopPropagation();
    setLightboxIndex(index);
    setLightboxOpen(true);
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-[60vh]">
        <Loader2 className="w-8 h-8 text-blue-500 animate-spin" />
      </div>
    );
  }

  return (
    <div className="space-y-8 pb-8">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 rounded-xl bg-purple-500/20 flex items-center justify-center">
            <Camera className="w-6 h-6 text-purple-400" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-white">Rush</h1>
            <p className="text-slate-500 text-sm">
              Generez des photos pour votre galerie
            </p>
          </div>
        </div>
        <ProjectBibleButton projectId={projectId} />
      </div>

      {/* Generator - Reuse QuickShotGenerator */}
      <QuickShotGenerator
        projectId={projectId}
        defaultAspectRatio={projectAspectRatio}
        onShotsGenerated={handleShotsGenerated}
        apiEndpoint={`/api/projects/${projectId}/rush`}
        title="Rush Generator"
        lockAspectRatio={true}
        description="Generez des photos avec @Personnage #Lieu !Reference"
        mode="multi"
      />

      {/* Images Grid */}
      {images.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-20 text-center">
          <div className="w-20 h-20 rounded-2xl bg-white/5 flex items-center justify-center mb-6">
            <Camera className="w-10 h-10 text-slate-600" />
          </div>
          <p className="text-slate-400 text-lg">Aucune image</p>
          <p className="text-slate-600 text-sm mt-1">
            Generez votre premiere photo avec le prompt ci-dessus
          </p>
        </div>
      ) : (
        <div>
          <h2 className="text-lg font-semibold text-white mb-4">
            Galerie ({images.length})
          </h2>

          <div className="columns-2 sm:columns-3 md:columns-4 lg:columns-5 gap-4 space-y-4">
            {images.map((image, index) => (
              <div
                key={image.id}
                className="break-inside-avoid relative group"
                onMouseEnter={() => setHoveredImage(image.id)}
                onMouseLeave={() => setHoveredImage(null)}
              >
                <div className="rounded-xl overflow-hidden border border-white/10 hover:border-white/20 transition-colors">
                  <StorageMedia
                    src={image.url}
                    alt={image.prompt || 'Rush media'}
                    className="w-full h-auto"
                    controls={false}
                    muted={true}
                    loop={true}
                    autoPlay={true}
                  />
                </div>

                {/* Hover actions */}
                {hoveredImage === image.id && (
                  <div className="absolute inset-0 bg-black/40 rounded-xl flex items-center justify-center gap-2">
                    <button
                      onClick={(e) => openLightbox(index, e)}
                      className="w-10 h-10 rounded-full bg-white/20 backdrop-blur flex items-center justify-center hover:bg-white/30 transition-colors"
                    >
                      <Maximize2 className="w-5 h-5 text-white" />
                    </button>
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        handleDelete(image.id);
                      }}
                      className="w-10 h-10 rounded-full bg-red-500/20 backdrop-blur flex items-center justify-center hover:bg-red-500/40 transition-colors"
                    >
                      <Trash2 className="w-5 h-5 text-red-400" />
                    </button>
                  </div>
                )}

                {/* Prompt preview */}
                {image.prompt && (
                  <div className="absolute bottom-0 left-0 right-0 p-2 bg-gradient-to-t from-black/80 to-transparent rounded-b-xl opacity-0 group-hover:opacity-100 transition-opacity">
                    <p className="text-[10px] text-white/80 truncate">
                      {image.prompt}
                    </p>
                  </div>
                )}
              </div>
            ))}
          </div>

          {/* Lightbox */}
          <Lightbox
            images={lightboxImages}
            initialIndex={lightboxIndex}
            isOpen={lightboxOpen}
            onClose={() => setLightboxOpen(false)}
            onDelete={handleDelete}
          />
        </div>
      )}
    </div>
  );
}
