apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: studio
  annotations:
    # For cert-manager (Let's Encrypt)
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # For traefik (k3s default)
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - studio.stevencreeks.com
      secretName: studio-tls
  rules:
    - host: studio.stevencreeks.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: studio
                port:
                  number: 80
